### ISSUE TITLE
Keep empty arguments as they are

### ISSUE THREAD

**Issue by heavywatal** [muellan/clipp#16]
Empty arguments seem to be dropped in parsing process (in `parser::operator()`, I guess). Is it possible to change this behavior on the user side and pass an empty argument `""` as is? If not, I would suggest it should be changed for the consistency and flexibility.

Code:
```cxx
int main(int argc, char* argv[]) {
    std::string optional = "default";
    std::string positional;
    auto cli = (
      clipp::option("-o", "--optional")
      & clipp::value(clipp::match::any, "label-o", optional),
      clipp::value("label-p", positional)
    );
    auto parsed = clipp::parse(argc, argv, cli);
    if (!parsed) std::cout << "ERROR!\n";
    clipp::debug::print(std::cout, parsed);
    std::cout << "optional: " << optional << "\n";
    std::cout << "positional: " << positional << "\n";
    return 0;
}
```

Product
```
% ./a.out -o "" hello
ERROR!
#1 -o -> -o
#3 hello -> label-o
label-p          [missing after 0]
optional: hello
positional:
```

I expect `optional: ` (empty) and `positional: hello`.
Thanks.

**Comment by muellan** [comment]
I guess you are right. It should behave like you expected it. That's why there is `clipp::match::any` and `clipp:match::nonempty`.

**Comment by heavywatal** [comment]
Thank you for the prompt response! I have confirmed it works.
