### ISSUE TITLE
Matching flags with similar prefix

### ISSUE THREAD

**Issue by resetnow** [muellan/clipp#21]
Let's assume we have the following interface:

```
  cli = (option("--flag"),
         option("--flag-extra", "--flag-extra=") & value)
```

Passing arguments `--flag --flag-extra=foo` will fail, because `--flag-extra=` will first partially match with `--flag` in `try_match_joined_sequence` – `prefix_match`. One option to fix this would be to reorder groups, or perhaps when the matched string is not exactly the same length we could continue iterating through arguments to find the longest match. What would be a good way to fix it?

**Comment by heavywatal** [comment]
I have the same issue and the PR #22 works.

**Comment by muellan** [comment]
Thanks for pointing this out. Sorry that it took me a while to get back to you. I pushed a fix that also includes some test cases.
