### ISSUE TITLE
Error while compiling with vs2015 default compiler

### ISSUE THREAD

**Issue by TechNiggo** [muellan/clipp#25]
in clipp.h:

Severity	Code	Description	Project	File	Line	Suppression State
Error	C3256	'npos': variable use does not produce a constant expression 
line: 101

Severity	Code	Description	Project	File	Line	Suppression State
Error	C3256	'npos': variable use does not produce a constant expression 
line: 122

Severity	Code	Description	Project	File	Line	Suppression State
Error	C2066	cast to function type is illegal	ArgumentParser	
line: 174

**Comment by muellan** [comment]
I'm sorry, but clipp does not support MSVC prior to version14.11.25503 (compiler 19.11.25547) which shipped with Visual Studio 2017.

Older Compilers from Microsoft have a **very incomplete** support for C++11 (`constexpr` is not properly supported, etc.)

To be honest, I have no intentions of supporting these ancient and non-standard-conforming compilers in 2019. I already don' t have enough time at the moment to finish the next version of clipp which should have much better user input error handling.

Maybe someone else is willing to put in the work of creating workarounds and isolating the critical code with preprocessor statements.
