### ISSUE TITLE
how to ignore arguments, like --undefok in glog

### ISSUE THREAD

**Issue by district10** [muellan/clipp#30]
glog `--undefok`: https://gflags.github.io/gflags/

> It is a fatal error to specify a flag on the commandline that has not been DEFINED somewhere in the executable. If you need that functionality for some reason -- say you want to use the same set of flags for several executables, but not all of them DEFINE every flag in your list -- you can specify --undefok to suppress the error.

**Comment by muellan** [comment]
You can catch arguments that don't match any other parameter with ```any_other```:

```cpp
std::vector<std::string> others;
bool ignoreUnknown = false;
auto cli = (
   option("-a"),
   /* ... more options */
   option("--undefdok").set(ignoreUnknown),
   any_other(others)
);

auto result = parse(argc, argv, cli);

const bool unknownOK = ignoreUnknown || others.empty();

if(result && unknownOK) {
    // OK
} 
else {
    // ERROR
}
```

**Comment by district10** [comment]
@muellan Thank you.
