### ISSUE TITLE
unused imports

### ISSUE THREAD

**Issue by someburner** [muellan/clipp#8]
For a lot of my projects I like to define `log()` so I can type as little as possible. This might be a bad idea, but nonetheless.. When I take it out `#include <cmath>` it compiles just fine (g++ 7.x), and the less imports the better IMO.

Edit: actually cloned and ran the `tests.py` file. And there a lot of errors popped up for missing imports. But for some, it seems the import is only needed by the test cpp files. In the case above, `values_conversion_test.cpp` failed, but putting the include into the test.cpp and it passed.

**Comment by someburner** [comment]
In fact, my the majority of these can be removed, unless I am missing something.

I get by with just this:

```cpp
#include <cstring>
#include <stack>
#include <sstream>
#include <functional>
```

The project I'm testing with has minimal includes, just `<iostream>`. These appear to not be necessary:

```cpp
#include <algorithm>
#include <cstdlib>
#include <cctype>
#include <cstring>
#include <iterator>
#include <utility>
#include <limits>
#include <vector>
#include <memory>
#include <string>
```

**Comment by muellan** [comment]
You are right `<cmath>` was no longer needed. I probably needed it a while back, but there is nothing that depends on it.
I'm curious: what was the problem with `log`? If you define your own `log` for your own types, you should do it in a separate namespace and ADL will do the rest. Or did you define your own `log` for builtin types?

**Comment by someburner** [comment]
yeah it was namespace issue with logarithmic log. I know it's in poor form, but I haven't gotten around to changing it. Another thing I was wondering- having you considered adding (the option of) escape codes to the man page, or other formatters? I hacked it in for fun by adding this to the `man_page` class:

```cpp
    std::string __bold_wht ="\033[1;38;40m"; // Bold white
    std::string __end = "\033[0m";

    man_page&
    append_section(string title, string content)
    {
        sections_.emplace_back(std::move(__bold_wht+title+__end), std::move(content));
        return *this;
    }
    //-----------------------------------------------------
    man_page&
    prepend_section(string title, string content)
    {
        sections_.emplace(sections_.begin(),
                          std::move(__bold_wht+title+__end), std::move(content));
        return *this;
    }
```
